name: run main.py

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 7-22 * * 1-5" # Every hour, between 07:00 AM and 10:59 PM, Monday through Friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: cache python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          NUMBER: ${{ secrets.NUMBER }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SMTP: ${{ secrets.SMTP }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LAST_UPDATE_DATE: ${{ vars.LAST_UPDATE_DATE }}
          LAST_UPDATE_DATE_VAR: "LAST_UPDATE_DATE"
        run: python trigger.py
